///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test2.EndModule
{
    /// <summary>
    ///The ExportENI recording.
    /// </summary>
    [TestModule("4f2e6381-3dd8-4df3-a8ac-5a0e373df03c", ModuleType.Recording, 1)]
    public partial class ExportENI : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test2.Test2Repository repository.
        /// </summary>
        public static Test2.Test2Repository repo = Test2.Test2Repository.Instance;

        static ExportENI instance = new ExportENI();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ExportENI()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ExportENI Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.ExportENI' at 20;16.", repo.MainForm.ExportENIInfo, new RecordItemIndex(0));
            repo.MainForm.ExportENI.Click("20;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '另存新檔.ToolBar1001' at 271;14.", repo.另存新檔.ToolBar1001Info, new RecordItemIndex(1));
            repo.另存新檔.ToolBar1001.Click("271;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}D:{RShiftKey up}\\'.", new RecordItemIndex(2));
            Keyboard.Press("{RShiftKey down}D:{RShiftKey up}\\");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}T{RShiftKey up}es'.", new RecordItemIndex(3));
            Keyboard.Press("{RShiftKey down}T{RShiftKey up}es");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 't{RShiftKey down}R{RShiftKey up}esult'.", new RecordItemIndex(4));
            Keyboard.Press("t{RShiftKey down}R{RShiftKey up}esult");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(5));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '另存新檔.Text1001' at 228;15.", repo.另存新檔.Text1001Info, new RecordItemIndex(6));
            repo.另存新檔.Text1001.Click("228;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}T{RShiftKey up}est' with focus on '另存新檔.Text1001'.", repo.另存新檔.Text1001Info, new RecordItemIndex(7));
            repo.另存新檔.Text1001.PressKeys("{RShiftKey down}T{RShiftKey up}est");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}' with focus on '另存新檔.Text1001'.", repo.另存新檔.Text1001Info, new RecordItemIndex(8));
            repo.另存新檔.Text1001.PressKeys("{NumPad2}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item '另存新檔.存檔S' at 47;11.", repo.另存新檔.存檔SInfo, new RecordItemIndex(9));
            repo.另存新檔.存檔S.MoveTo("47;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item '另存新檔.存檔S' at 47;11.", repo.另存新檔.存檔SInfo, new RecordItemIndex(10));
            repo.另存新檔.存檔S.MoveTo("47;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(11));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
}
