///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test2.InitModule
{
    /// <summary>
    /// The class representing the InitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
    [RepositoryFolder("06125b2e-82b2-4af7-ab62-e6a19e9c338d")]
    public partial class InitRepository : RepoGenBaseFolder
    {
        static InitRepository instance = new InitRepository();
        InitRepositoryFolders.VisualStudioMainWindowAppFolder _visualstudiomainwindow;

        /// <summary>
        /// Gets the singleton class instance representing the InitRepository element repository.
        /// </summary>
        [RepositoryFolder("06125b2e-82b2-4af7-ab62-e6a19e9c338d")]
        public static InitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public InitRepository() 
            : base("InitRepository", "/", null, 0, false, "06125b2e-82b2-4af7-ab62-e6a19e9c338d", ".\\RepositoryImages\\InitRepository06125b2e.rximgres")
        {
            _visualstudiomainwindow = new InitRepositoryFolders.VisualStudioMainWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("06125b2e-82b2-4af7-ab62-e6a19e9c338d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The VisualStudioMainWindow folder.
        /// </summary>
        [RepositoryFolder("ae8631c6-a227-430f-8c4c-19f55aa8255c")]
        public virtual InitRepositoryFolders.VisualStudioMainWindowAppFolder VisualStudioMainWindow
        {
            get { return _visualstudiomainwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
    public partial class InitRepositoryFolders
    {
        /// <summary>
        /// The VisualStudioMainWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("ae8631c6-a227-430f-8c4c-19f55aa8255c")]
        public partial class VisualStudioMainWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _partfocustargetInfo;

            /// <summary>
            /// Creates a new VisualStudioMainWindow  folder.
            /// </summary>
            public VisualStudioMainWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VisualStudioMainWindow", "/form[@automationid='VisualStudioMainWindow']", parentFolder, 30000, null, true, "ae8631c6-a227-430f-8c4c-19f55aa8255c", "")
            {
                _partfocustargetInfo = new RepoItemInfo(this, "PARTFocusTarget", "?/?/toolbar[@name='標準']/button[@name='偵錯目標']/?/?/menuitem[@automationid='PART_FocusTarget']", 30000, null, "bd12be25-2dca-446d-9b3f-1e4399b511b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ae8631c6-a227-430f-8c4c-19f55aa8255c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ae8631c6-a227-430f-8c4c-19f55aa8255c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTFocusTarget item.
            /// </summary>
            [RepositoryItem("bd12be25-2dca-446d-9b3f-1e4399b511b6")]
            public virtual Ranorex.MenuItem PARTFocusTarget
            {
                get
                {
                    return _partfocustargetInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The PARTFocusTarget item info.
            /// </summary>
            [RepositoryItemInfo("bd12be25-2dca-446d-9b3f-1e4399b511b6")]
            public virtual RepoItemInfo PARTFocusTargetInfo
            {
                get
                {
                    return _partfocustargetInfo;
                }
            }
        }

    }
}