///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test2.TestCaseModule
{
    /// <summary>
    ///The Slave3 recording.
    /// </summary>
    [TestModule("2e0326cf-d212-4a44-8424-8fe561cb59cc", ModuleType.Recording, 1)]
    public partial class Slave3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test2.Test3Repository repository.
        /// </summary>
        public static Test2.Test3Repository repo = Test2.Test3Repository.Instance;

        static Slave3 instance = new Slave3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Slave3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Slave3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.R1EC55000x100000' at 20;7.", repo.MainForm.R1EC55000x100000Info, new RecordItemIndex(0));
            repo.MainForm.R1EC55000x100000.Click("20;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MainForm.R1EC55000x100000' at 20;7.", repo.MainForm.R1EC55000x100000Info, new RecordItemIndex(1));
            repo.MainForm.R1EC55000x100000.DoubleClick("20;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
