///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test2.TestCaseModule
{
    /// <summary>
    ///The Slave3 recording.
    /// </summary>
    [TestModule("2e0326cf-d212-4a44-8424-8fe561cb59cc", ModuleType.Recording, 1)]
    public partial class Slave3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test2.Test2Repository repository.
        /// </summary>
        public static Test2.Test2Repository repo = Test2.Test2Repository.Instance;

        static Slave3 instance = new Slave3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Slave3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Slave3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.SGDVE1CoEDrive0x40000' at 45;7.", repo.MainForm.SGDVE1CoEDrive0x40000Info, new RecordItemIndex(0));
            repo.MainForm.SGDVE1CoEDrive0x40000.Click("45;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MainForm.SGDVE1CoEDrive0x40000' at 45;6.", repo.MainForm.SGDVE1CoEDrive0x40000Info, new RecordItemIndex(1));
            repo.MainForm.SGDVE1CoEDrive0x40000.DoubleClick("45;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.UpDownEdit' at 57;9.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(2));
            repo.MainForm.NWForm.UpDownEdit.Click("57;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{NumPad4}' with focus on 'MainForm.NWForm.UpDownEdit'.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(3));
            repo.MainForm.NWForm.UpDownEdit.PressKeys("{Back}{NumPad4}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.PDOMapping' at 32;13.", repo.MainForm.NWForm.PDOMappingInfo, new RecordItemIndex(4));
            repo.MainForm.NWForm.PDOMapping.Click("32;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainForm.NWForm.Position' at 8;17.", repo.MainForm.NWForm.PositionInfo, new RecordItemIndex(5));
            repo.MainForm.NWForm.Position.MoveTo("8;17");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainForm.NWForm.Position' at 8;45.", repo.MainForm.NWForm.PositionInfo, new RecordItemIndex(6));
            repo.MainForm.NWForm.Position.MoveTo("8;45");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainForm.NWForm.Position1' at 9;17.", repo.MainForm.NWForm.Position1Info, new RecordItemIndex(7));
            repo.MainForm.NWForm.Position1.MoveTo("9;17");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainForm.NWForm.Position1' at 13;58.", repo.MainForm.NWForm.Position1Info, new RecordItemIndex(8));
            repo.MainForm.NWForm.Position1.MoveTo("13;58");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.NameRow9' at 14;8.", repo.MainForm.NWForm.NameRow9Info, new RecordItemIndex(9));
            repo.MainForm.NWForm.NameRow9.Click("14;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainForm.NWForm.Position1' at 11;23.", repo.MainForm.NWForm.Position1Info, new RecordItemIndex(10));
            repo.MainForm.NWForm.Position1.MoveTo("11;23");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainForm.NWForm.Position1' at 8;60.", repo.MainForm.NWForm.Position1Info, new RecordItemIndex(11));
            repo.MainForm.NWForm.Position1.MoveTo("8;60");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.NameRow15' at 10;10.", repo.MainForm.NWForm.NameRow15Info, new RecordItemIndex(12));
            repo.MainForm.NWForm.NameRow15.Click("10;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.Edit' at 54;20.", repo.MainForm.NWForm.EditInfo, new RecordItemIndex(13));
            repo.MainForm.NWForm.Edit.Click("54;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PdoSettingForm.ButtonAdd' at 52;6.", repo.PdoSettingForm.ButtonAddInfo, new RecordItemIndex(14));
            repo.PdoSettingForm.ButtonAdd.Click("52;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddPdoEntryForm.Position' at 9;28.", repo.AddPdoEntryForm.PositionInfo, new RecordItemIndex(15));
            repo.AddPdoEntryForm.Position.MoveTo("9;28");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddPdoEntryForm.TableLayoutPanel11' at 638;337.", repo.AddPdoEntryForm.TableLayoutPanel11Info, new RecordItemIndex(16));
            repo.AddPdoEntryForm.TableLayoutPanel11.MoveTo("638;337");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPdoEntryForm.IndexRow25' at 24;13.", repo.AddPdoEntryForm.IndexRow25Info, new RecordItemIndex(17));
            repo.AddPdoEntryForm.IndexRow25.Click("24;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddPdoEntryForm.ButtonOk' at 49;13.", repo.AddPdoEntryForm.ButtonOkInfo, new RecordItemIndex(18));
            repo.AddPdoEntryForm.ButtonOk.Click("49;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'PdoSettingForm.ButtonOK' at 58;3.", repo.PdoSettingForm.ButtonOKInfo, new RecordItemIndex(19));
            repo.PdoSettingForm.ButtonOK.MoveTo("58;3");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'PdoSettingForm.ButtonOK' at 58;3.", repo.PdoSettingForm.ButtonOKInfo, new RecordItemIndex(20));
            repo.PdoSettingForm.ButtonOK.MoveTo("58;3");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainForm.NWForm.Position1' at 7;19.", repo.MainForm.NWForm.Position1Info, new RecordItemIndex(21));
            repo.MainForm.NWForm.Position1.MoveTo("7;19");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainForm.NWForm.LineDown1' at 5;5.", repo.MainForm.NWForm.LineDown1Info, new RecordItemIndex(22));
            repo.MainForm.NWForm.LineDown1.MoveTo("5;5");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.IOMapping' at 49;13.", repo.MainForm.NWForm.IOMappingInfo, new RecordItemIndex(23));
            repo.MainForm.NWForm.IOMapping.Click("49;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.SymbolRow4' at 39;7.", repo.MainForm.NWForm.SymbolRow4Info, new RecordItemIndex(24));
            repo.MainForm.NWForm.SymbolRow4.Click("39;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'haha' with focus on 'MainForm.NWForm.SymbolRow4'.", repo.MainForm.NWForm.SymbolRow4Info, new RecordItemIndex(25));
            repo.MainForm.NWForm.SymbolRow4.PressKeys("haha");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'MainForm.NWForm.SymbolRow4'.", repo.MainForm.NWForm.SymbolRow4Info, new RecordItemIndex(26));
            repo.MainForm.NWForm.SymbolRow4.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.InitCommands' at 56;6.", repo.MainForm.NWForm.InitCommandsInfo, new RecordItemIndex(27));
            repo.MainForm.NWForm.InitCommands.Click("56;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.ValueRow0' at 12;12.", repo.MainForm.NWForm.ValueRow0Info, new RecordItemIndex(28));
            repo.MainForm.NWForm.ValueRow0.Click("12;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MainForm.NWForm.ValueRow0' at 12;12.", repo.MainForm.NWForm.ValueRow0Info, new RecordItemIndex(29));
            repo.MainForm.NWForm.ValueRow0.DoubleClick("12;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.Edit1' at 60;12.", repo.MainForm.NWForm.Edit1Info, new RecordItemIndex(30));
            repo.MainForm.NWForm.Edit1.Click("60;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddCoEInitCommandForm.Panel11.TBData' at 38;10.", repo.AddCoEInitCommandForm.Panel11.TBDataInfo, new RecordItemIndex(31));
            repo.AddCoEInitCommandForm.Panel11.TBData.MoveTo("38;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddCoEInitCommandForm.Panel11.Panel1' at 82;70.", repo.AddCoEInitCommandForm.Panel11.Panel1Info, new RecordItemIndex(32));
            repo.AddCoEInitCommandForm.Panel11.Panel1.MoveTo("82;70");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad1}' with focus on 'AddCoEInitCommandForm.Panel11.TBData'.", repo.AddCoEInitCommandForm.Panel11.TBDataInfo, new RecordItemIndex(33));
            repo.AddCoEInitCommandForm.Panel11.TBData.PressKeys("{NumPad1}{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddCoEInitCommandForm.ButtonOk' at 56;8.", repo.AddCoEInitCommandForm.ButtonOkInfo, new RecordItemIndex(34));
            repo.AddCoEInitCommandForm.ButtonOk.Click("56;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.ValueRow2' at 21;8.", repo.MainForm.NWForm.ValueRow2Info, new RecordItemIndex(35));
            repo.MainForm.NWForm.ValueRow2.Click("21;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.Edit1' at 39;8.", repo.MainForm.NWForm.Edit1Info, new RecordItemIndex(36));
            repo.MainForm.NWForm.Edit1.Click("39;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddCoEInitCommandForm.Panel11.TBData' at 32;13.", repo.AddCoEInitCommandForm.Panel11.TBDataInfo, new RecordItemIndex(37));
            repo.AddCoEInitCommandForm.Panel11.TBData.MoveTo("32;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddCoEInitCommandForm.Panel11.LbValue' at 41;16.", repo.AddCoEInitCommandForm.Panel11.LbValueInfo, new RecordItemIndex(38));
            repo.AddCoEInitCommandForm.Panel11.LbValue.MoveTo("41;16");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad5}' with focus on 'AddCoEInitCommandForm.Panel11.TBData'.", repo.AddCoEInitCommandForm.Panel11.TBDataInfo, new RecordItemIndex(39));
            repo.AddCoEInitCommandForm.Panel11.TBData.PressKeys("{NumPad5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddCoEInitCommandForm.ButtonOk' at 50;8.", repo.AddCoEInitCommandForm.ButtonOkInfo, new RecordItemIndex(40));
            repo.AddCoEInitCommandForm.ButtonOk.Click("50;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.ButtonAdd1' at 71;15.", repo.MainForm.NWForm.ButtonAdd1Info, new RecordItemIndex(41));
            repo.MainForm.NWForm.ButtonAdd1.Click("71;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddCoEInitCommandForm.Position' at 8;10.", repo.AddCoEInitCommandForm.PositionInfo, new RecordItemIndex(42));
            repo.AddCoEInitCommandForm.Position.MoveTo("8;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddCoEInitCommandForm.LineDown' at 15;11.", repo.AddCoEInitCommandForm.LineDownInfo, new RecordItemIndex(43));
            repo.AddCoEInitCommandForm.LineDown.MoveTo("15;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddCoEInitCommandForm.IndexRow180' at 36;9.", repo.AddCoEInitCommandForm.IndexRow180Info, new RecordItemIndex(44));
            repo.AddCoEInitCommandForm.IndexRow180.Click("36;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddCoEInitCommandForm.ButtonOk' at 29;6.", repo.AddCoEInitCommandForm.ButtonOkInfo, new RecordItemIndex(45));
            repo.AddCoEInitCommandForm.ButtonOk.Click("29;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.ValueRow3' at 20;11.", repo.MainForm.NWForm.ValueRow3Info, new RecordItemIndex(46));
            repo.MainForm.NWForm.ValueRow3.Click("20;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.Edit1' at 40;21.", repo.MainForm.NWForm.Edit1Info, new RecordItemIndex(47));
            repo.MainForm.NWForm.Edit1.Click("40;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddCoEInitCommandForm.Panel11.TBData' at 49;13.", repo.AddCoEInitCommandForm.Panel11.TBDataInfo, new RecordItemIndex(48));
            repo.AddCoEInitCommandForm.Panel11.TBData.MoveTo("49;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddCoEInitCommandForm.Panel11.LbValue' at 30;13.", repo.AddCoEInitCommandForm.Panel11.LbValueInfo, new RecordItemIndex(49));
            repo.AddCoEInitCommandForm.Panel11.LbValue.MoveTo("30;13");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad0}' with focus on 'AddCoEInitCommandForm.Panel11.TBData'.", repo.AddCoEInitCommandForm.Panel11.TBDataInfo, new RecordItemIndex(50));
            repo.AddCoEInitCommandForm.Panel11.TBData.PressKeys("{NumPad1}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddCoEInitCommandForm.ButtonOk' at 62;6.", repo.AddCoEInitCommandForm.ButtonOkInfo, new RecordItemIndex(51));
            repo.AddCoEInitCommandForm.ButtonOk.MoveTo("62;6");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddCoEInitCommandForm.ButtonOk' at 62;6.", repo.AddCoEInitCommandForm.ButtonOkInfo, new RecordItemIndex(52));
            repo.AddCoEInitCommandForm.ButtonOk.MoveTo("62;6");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.Parameters' at 46;5.", repo.MainForm.NWForm.ParametersInfo, new RecordItemIndex(53));
            repo.MainForm.NWForm.Parameters.Click("46;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.ButtonAdd' at 29;19.", repo.MainForm.NWForm.ButtonAddInfo, new RecordItemIndex(54));
            repo.MainForm.NWForm.ButtonAdd.Click("29;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddSlaveParameterForm.Position' at 8;9.", repo.AddSlaveParameterForm.PositionInfo, new RecordItemIndex(55));
            repo.AddSlaveParameterForm.Position.MoveTo("8;9");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddSlaveParameterForm.Position' at 16;308.", repo.AddSlaveParameterForm.PositionInfo, new RecordItemIndex(56));
            repo.AddSlaveParameterForm.Position.MoveTo("16;308");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddSlaveParameterForm.Node229' at 45;12.", repo.AddSlaveParameterForm.Node229Info, new RecordItemIndex(57));
            repo.AddSlaveParameterForm.Node229.Click("45;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddSlaveParameterForm.ButtonOk' at 26;16.", repo.AddSlaveParameterForm.ButtonOkInfo, new RecordItemIndex(58));
            repo.AddSlaveParameterForm.ButtonOk.Click("26;16");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
