///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test2.TestCaseModule
{
    /// <summary>
    ///The Slave4 recording.
    /// </summary>
    [TestModule("939ee3b2-19d0-4ecb-bf35-a0997a89ece0", ModuleType.Recording, 1)]
    public partial class Slave4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test2.Test2Repository repository.
        /// </summary>
        public static Test2.Test2Repository repo = Test2.Test2Repository.Instance;

        static Slave4 instance = new Slave4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Slave4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Slave4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.R1EC55000x100000' at 39;5.", repo.MainForm.R1EC55000x100000Info, new RecordItemIndex(0));
            repo.MainForm.R1EC55000x100000.Click("39;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MainForm.R1EC55000x100000' at 39;5.", repo.MainForm.R1EC55000x100000Info, new RecordItemIndex(1));
            repo.MainForm.R1EC55000x100000.DoubleClick("39;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.UpDownEdit' at 55;7.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(2));
            repo.MainForm.NWForm.UpDownEdit.Click("55;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainForm.NWForm.UpDownEdit' at 55;5.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(3));
            repo.MainForm.NWForm.UpDownEdit.MoveTo("55;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainForm.Outline1' at 98;837.", repo.MainForm.Outline1Info, new RecordItemIndex(4));
            repo.MainForm.Outline1.MoveTo("98;837");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2}{NumPad2}{NumPad2}' with focus on 'MainForm.NWForm.UpDownEdit'.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(5));
            repo.MainForm.NWForm.UpDownEdit.PressKeys("{NumPad2}{NumPad2}{NumPad2}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'MainForm.NWForm.UpDownEdit'.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(6));
            repo.MainForm.NWForm.UpDownEdit.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.TabPageGeneral' at 424;218.", repo.MainForm.NWForm.TabPageGeneralInfo, new RecordItemIndex(7));
            repo.MainForm.NWForm.TabPageGeneral.Click("424;218");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Diagram1' at 779;568.", repo.MainForm.Diagram1Info, new RecordItemIndex(8));
            repo.MainForm.Diagram1.Click("779;568");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
