///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test2.TestCaseModule
{
    /// <summary>
    ///The Slave1 recording.
    /// </summary>
    [TestModule("410edec6-159d-479d-901d-41efa2c60f44", ModuleType.Recording, 1)]
    public partial class Slave1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Test2.Test2Repository repository.
        /// </summary>
        public static Test2.Test2Repository repo = Test2.Test2Repository.Instance;

        static Slave1 instance = new Slave1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Slave1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Slave1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Outline' at 14;28.", repo.MainForm.OutlineInfo, new RecordItemIndex(0));
            repo.MainForm.Outline.Click("14;28");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MainForm.ASDAA2ECoEDrive0x2040608' at 18;6.", repo.MainForm.ASDAA2ECoEDrive0x2040608Info, new RecordItemIndex(1));
            repo.MainForm.ASDAA2ECoEDrive0x2040608.DoubleClick("18;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.UpDownEdit' at 32;8.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(2));
            repo.MainForm.NWForm.UpDownEdit.Click("32;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{NumPad5}' with focus on 'MainForm.NWForm.UpDownEdit'.", repo.MainForm.NWForm.UpDownEditInfo, new RecordItemIndex(3));
            repo.MainForm.NWForm.UpDownEdit.PressKeys("{Back}{NumPad5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.PDOMapping' at 64;12.", repo.MainForm.NWForm.PDOMappingInfo, new RecordItemIndex(4));
            repo.MainForm.NWForm.PDOMapping.Click("64;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.NameRow0' at 14;7.", repo.MainForm.NWForm.NameRow0Info, new RecordItemIndex(5));
            repo.MainForm.NWForm.NameRow0.Click("14;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.NameRow01' at 13;10.", repo.MainForm.NWForm.NameRow01Info, new RecordItemIndex(6));
            repo.MainForm.NWForm.NameRow01.Click("13;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.Parameters' at 31;9.", repo.MainForm.NWForm.ParametersInfo, new RecordItemIndex(7));
            repo.MainForm.NWForm.Parameters.Click("31;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.NWForm.ButtonAdd' at 51;14.", repo.MainForm.NWForm.ButtonAddInfo, new RecordItemIndex(8));
            repo.MainForm.NWForm.ButtonAdd.Click("51;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AddSlaveParameterForm.Position' at 9;9.", repo.AddSlaveParameterForm.PositionInfo, new RecordItemIndex(9));
            repo.AddSlaveParameterForm.Position.MoveTo("9;9");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AddSlaveParameterForm.TableLayoutPanel2' at 652;418.", repo.AddSlaveParameterForm.TableLayoutPanel2Info, new RecordItemIndex(10));
            repo.AddSlaveParameterForm.TableLayoutPanel2.MoveTo("652;418");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddSlaveParameterForm.Node553' at 44;10.", repo.AddSlaveParameterForm.Node553Info, new RecordItemIndex(11));
            repo.AddSlaveParameterForm.Node553.Click("44;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddSlaveParameterForm.ButtonOk' at 41;10.", repo.AddSlaveParameterForm.ButtonOkInfo, new RecordItemIndex(12));
            repo.AddSlaveParameterForm.ButtonOk.Click("41;10");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
}
