///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test2.TestCaseModule
{
    /// <summary>
    /// The class representing the TestCaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
    [RepositoryFolder("8e410807-1216-43c2-b58b-47d799db0f9e")]
    public partial class TestCaseRepository : RepoGenBaseFolder
    {
        static TestCaseRepository instance = new TestCaseRepository();
        TestCaseRepositoryFolders.EIPBuilderVshostAppFolder _eipbuildervshost;
        TestCaseRepositoryFolders.MainFormAppFolder _mainform;

        /// <summary>
        /// Gets the singleton class instance representing the TestCaseRepository element repository.
        /// </summary>
        [RepositoryFolder("8e410807-1216-43c2-b58b-47d799db0f9e")]
        public static TestCaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestCaseRepository() 
            : base("TestCaseRepository", "/", null, 0, false, "8e410807-1216-43c2-b58b-47d799db0f9e", ".\\RepositoryImages\\TestCaseRepository8e410807.rximgres")
        {
            _eipbuildervshost = new TestCaseRepositoryFolders.EIPBuilderVshostAppFolder(this);
            _mainform = new TestCaseRepositoryFolders.MainFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8e410807-1216-43c2-b58b-47d799db0f9e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EIPBuilderVshost folder.
        /// </summary>
        [RepositoryFolder("5e535f8d-1884-4bbb-97f6-e060163f3647")]
        public virtual TestCaseRepositoryFolders.EIPBuilderVshostAppFolder EIPBuilderVshost
        {
            get { return _eipbuildervshost; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("5123ec99-43f0-4585-9eb8-c3fbfec4f251")]
        public virtual TestCaseRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.0.2")]
    public partial class TestCaseRepositoryFolders
    {
        /// <summary>
        /// The EIPBuilderVshostAppFolder folder.
        /// </summary>
        [RepositoryFolder("5e535f8d-1884-4bbb-97f6-e060163f3647")]
        public partial class EIPBuilderVshostAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listitem4000Info;

            /// <summary>
            /// Creates a new EIPBuilderVshost  folder.
            /// </summary>
            public EIPBuilderVshostAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EIPBuilderVshost", "/form[@processname='EIP Builder.vshost' and @controltypename='ComboBoxPopupListBoxForm']", parentFolder, 30000, null, true, "5e535f8d-1884-4bbb-97f6-e060163f3647", "")
            {
                _listitem4000Info = new RepoItemInfo(this, "ListItem4000", "?/?/list[@accessiblename='']/listitem[@accessiblename='4000']", 30000, null, "ed07dbcf-e881-4709-81de-ff164636824d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e535f8d-1884-4bbb-97f6-e060163f3647")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e535f8d-1884-4bbb-97f6-e060163f3647")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItem4000 item.
            /// </summary>
            [RepositoryItem("ed07dbcf-e881-4709-81de-ff164636824d")]
            public virtual Ranorex.ListItem ListItem4000
            {
                get
                {
                    return _listitem4000Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem4000 item info.
            /// </summary>
            [RepositoryItemInfo("ed07dbcf-e881-4709-81de-ff164636824d")]
            public virtual RepoItemInfo ListItem4000Info
            {
                get
                {
                    return _listitem4000Info;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("5123ec99-43f0-4585-9eb8-c3fbfec4f251")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            TestCaseRepositoryFolders.NWFormFolder _nwform;
            RepoItemInfo _diagram1Info;
            RepoItemInfo _openInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _pushbuttonInfo;
            RepoItemInfo _asdaa2ecoedrive0x2040608Info;
            RepoItemInfo _text1Info;
            RepoItemInfo _prodlistpanelInfo;
            RepoItemInfo _sgdve1coedrive0x40000Info;
            RepoItemInfo _sgdve1coedrive0x10000Info;
            RepoItemInfo _documentshostInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "5123ec99-43f0-4585-9eb8-c3fbfec4f251", "")
            {
                _nwform = new TestCaseRepositoryFolders.NWFormFolder(this);
                _diagram1Info = new RepoItemInfo(this, "Diagram1", ".//form[@controlname='NWForm']/?/?/container[@controlname='panel1']/form[@controlname='NetworkDiagram']/element[@controlname='diagram1']", 30000, null, "d2b6393b-fb49-4ed8-88ce-e05062e090f1");
                _openInfo = new RepoItemInfo(this, "Open", ".//container[@controlname='UserControl_Form']/form[@controlname='NWForm']/container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='MasterConfigForm']/?/?/tabpage[@controlname='tabPage_General']//combobox[@accessiblename='2000']/button[@accessiblename='Open']", 30000, null, "992ff7ce-71d5-4f30-b782-3e4316db9109");
                _closeInfo = new RepoItemInfo(this, "Close", ".//container[@controlname='UserControl_Form']/form[@controlname='NWForm']/container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='MasterConfigForm']/?/?/tabpage[@controlname='tabPage_General']//combobox[@accessiblename='2000']/button[@accessiblename='Close']", 30000, null, "3256401f-575a-4d92-a332-1ecbdbd123b8");
                _textInfo = new RepoItemInfo(this, "Text", "container[@controlname='prodListPanel']/?/?/container[@controlname='UserControl_Form']/form[@controlname='ProdListForm']//text[@accessiblerole='Text' and @controltext='-E']", 30000, null, "84c8b28a-1195-445f-b175-d67493d013e1");
                _pushbuttonInfo = new RepoItemInfo(this, "PushButton", "container[@controlname='prodListPanel']/?/?/container[@controlname='UserControl_Form']/form[@controlname='ProdListForm']//button[@accessiblename='']", 30000, null, "f3b63f67-11d7-4a69-a6f7-c34ef99ae0cc");
                _asdaa2ecoedrive0x2040608Info = new RepoItemInfo(this, "ASDAA2ECoEDrive0x2040608", "container[@controlname='prodListPanel']//form[@controlname='ProdListForm']/?/?/tree[@controlname='treeView_ProdList']/tree[@accessiblerole='Outline']/?/?/treeitem[@accessiblename~'^ASDA-A2-E\\ CoE\\ Drive\\ \\(0x20']", 30000, null, "49c96674-924d-4e26-83c7-1f1abdfd4792");
                _text1Info = new RepoItemInfo(this, "Text1", "container[@controlname='prodListPanel']/?/?/container[@controlname='UserControl_Form']/form[@controlname='ProdListForm']//text[@accessiblerole='Text']", 30000, null, "4f17726e-d046-4f83-965e-0a877cc6752f");
                _prodlistpanelInfo = new RepoItemInfo(this, "ProdListPanel", "container[@controlname='prodListPanel']", 30000, null, "f4a5e46e-81f1-42ec-85bb-c8b934cd0959");
                _sgdve1coedrive0x40000Info = new RepoItemInfo(this, "SGDVE1CoEDrive0x40000", "container[@controlname='prodListPanel']//form[@controlname='ProdListForm']/?/?/tree[@controlname='treeView_ProdList']/tree[@accessiblerole='Outline']//treeitem[@accessiblename~'^SGDV-E1\\ CoE\\ Drive\\ \\(0x4000']", 30000, null, "49475c15-3a18-45f6-a357-9e6a22fb574b");
                _sgdve1coedrive0x10000Info = new RepoItemInfo(this, "SGDVE1CoEDrive0x10000", "container[@controlname='prodListPanel']//form[@controlname='ProdListForm']/?/?/tree[@controlname='treeView_ProdList']/tree[@accessiblerole='Outline']//treeitem[@accessiblename~'^SGDV-E1\\ CoE\\ Drive\\ \\(0x1000']", 30000, null, "5348e8aa-59e1-4018-bb5a-c2447516955f");
                _documentshostInfo = new RepoItemInfo(this, "DocumentsHost", "element[@controltypename='DocumentsHost']", 30000, null, "c9e2a044-8725-4556-afb7-97a90245b9b1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5123ec99-43f0-4585-9eb8-c3fbfec4f251")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5123ec99-43f0-4585-9eb8-c3fbfec4f251")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Diagram1 item.
            /// </summary>
            [RepositoryItem("d2b6393b-fb49-4ed8-88ce-e05062e090f1")]
            public virtual Ranorex.Unknown Diagram1
            {
                get
                {
                    return _diagram1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Diagram1 item info.
            /// </summary>
            [RepositoryItemInfo("d2b6393b-fb49-4ed8-88ce-e05062e090f1")]
            public virtual RepoItemInfo Diagram1Info
            {
                get
                {
                    return _diagram1Info;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("992ff7ce-71d5-4f30-b782-3e4316db9109")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("992ff7ce-71d5-4f30-b782-3e4316db9109")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("3256401f-575a-4d92-a332-1ecbdbd123b8")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("3256401f-575a-4d92-a332-1ecbdbd123b8")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("84c8b28a-1195-445f-b175-d67493d013e1")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("84c8b28a-1195-445f-b175-d67493d013e1")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The PushButton item.
            /// </summary>
            [RepositoryItem("f3b63f67-11d7-4a69-a6f7-c34ef99ae0cc")]
            public virtual Ranorex.Button PushButton
            {
                get
                {
                    return _pushbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton item info.
            /// </summary>
            [RepositoryItemInfo("f3b63f67-11d7-4a69-a6f7-c34ef99ae0cc")]
            public virtual RepoItemInfo PushButtonInfo
            {
                get
                {
                    return _pushbuttonInfo;
                }
            }

            /// <summary>
            /// The ASDAA2ECoEDrive0x2040608 item.
            /// </summary>
            [RepositoryItem("49c96674-924d-4e26-83c7-1f1abdfd4792")]
            public virtual Ranorex.TreeItem ASDAA2ECoEDrive0x2040608
            {
                get
                {
                    return _asdaa2ecoedrive0x2040608Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ASDAA2ECoEDrive0x2040608 item info.
            /// </summary>
            [RepositoryItemInfo("49c96674-924d-4e26-83c7-1f1abdfd4792")]
            public virtual RepoItemInfo ASDAA2ECoEDrive0x2040608Info
            {
                get
                {
                    return _asdaa2ecoedrive0x2040608Info;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("4f17726e-d046-4f83-965e-0a877cc6752f")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("4f17726e-d046-4f83-965e-0a877cc6752f")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The ProdListPanel item.
            /// </summary>
            [RepositoryItem("f4a5e46e-81f1-42ec-85bb-c8b934cd0959")]
            public virtual Ranorex.Container ProdListPanel
            {
                get
                {
                    return _prodlistpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ProdListPanel item info.
            /// </summary>
            [RepositoryItemInfo("f4a5e46e-81f1-42ec-85bb-c8b934cd0959")]
            public virtual RepoItemInfo ProdListPanelInfo
            {
                get
                {
                    return _prodlistpanelInfo;
                }
            }

            /// <summary>
            /// The SGDVE1CoEDrive0x40000 item.
            /// </summary>
            [RepositoryItem("49475c15-3a18-45f6-a357-9e6a22fb574b")]
            public virtual Ranorex.TreeItem SGDVE1CoEDrive0x40000
            {
                get
                {
                    return _sgdve1coedrive0x40000Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SGDVE1CoEDrive0x40000 item info.
            /// </summary>
            [RepositoryItemInfo("49475c15-3a18-45f6-a357-9e6a22fb574b")]
            public virtual RepoItemInfo SGDVE1CoEDrive0x40000Info
            {
                get
                {
                    return _sgdve1coedrive0x40000Info;
                }
            }

            /// <summary>
            /// The SGDVE1CoEDrive0x10000 item.
            /// </summary>
            [RepositoryItem("5348e8aa-59e1-4018-bb5a-c2447516955f")]
            public virtual Ranorex.TreeItem SGDVE1CoEDrive0x10000
            {
                get
                {
                    return _sgdve1coedrive0x10000Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SGDVE1CoEDrive0x10000 item info.
            /// </summary>
            [RepositoryItemInfo("5348e8aa-59e1-4018-bb5a-c2447516955f")]
            public virtual RepoItemInfo SGDVE1CoEDrive0x10000Info
            {
                get
                {
                    return _sgdve1coedrive0x10000Info;
                }
            }

            /// <summary>
            /// The DocumentsHost item.
            /// </summary>
            [RepositoryItem("c9e2a044-8725-4556-afb7-97a90245b9b1")]
            public virtual Ranorex.Unknown DocumentsHost
            {
                get
                {
                    return _documentshostInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The DocumentsHost item info.
            /// </summary>
            [RepositoryItemInfo("c9e2a044-8725-4556-afb7-97a90245b9b1")]
            public virtual RepoItemInfo DocumentsHostInfo
            {
                get
                {
                    return _documentshostInfo;
                }
            }

            /// <summary>
            /// The NWForm folder.
            /// </summary>
            [RepositoryFolder("9e6d84de-866b-457e-bd99-dd691e0e98c6")]
            public virtual TestCaseRepositoryFolders.NWFormFolder NWForm
            {
                get { return _nwform; }
            }
        }

        /// <summary>
        /// The NWFormFolder folder.
        /// </summary>
        [RepositoryFolder("9e6d84de-866b-457e-bd99-dd691e0e98c6")]
        public partial class NWFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _generalInfo;
            RepoItemInfo _pdomappingInfo;
            RepoItemInfo _tabpagegeneralInfo;
            RepoItemInfo _namerow0Info;
            RepoItemInfo _namerow01Info;
            RepoItemInfo _parametersInfo;
            RepoItemInfo _buttonaddInfo;
            RepoItemInfo _positionInfo;
            RepoItemInfo _namerow12Info;
            RepoItemInfo _position1Info;
            RepoItemInfo _namerow9Info;
            RepoItemInfo _iomappingInfo;
            RepoItemInfo _symbolrow0Info;
            RepoItemInfo _symbolrow1Info;
            RepoItemInfo _selecttheoutputsInfo;
            RepoItemInfo _initcommandsInfo;
            RepoItemInfo _indexrow1Info;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _linedownInfo;
            RepoItemInfo _linedown1Info;
            RepoItemInfo _namerow15Info;
            RepoItemInfo _editInfo;
            RepoItemInfo _tablelayoutpanel3Info;
            RepoItemInfo _namerow18Info;

            /// <summary>
            /// Creates a new NWForm  folder.
            /// </summary>
            public NWFormFolder(RepoGenBaseFolder parentFolder) :
                    base("NWForm", ".//container[@controlname='UserControl_Form']/form[@controlname='NWForm']", parentFolder, 30000, null, false, "9e6d84de-866b-457e-bd99-dd691e0e98c6", "")
            {
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_General']/container[@controlname='numUpDown_NodeId']/text[@controlname='upDownEdit']", 30000, null, "2d06c920-6777-4f22-b40b-350b0d7dfc05");
                _generalInfo = new RepoItemInfo(this, "General", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@accessiblename='General']", 30000, null, "8a313465-c03e-497b-abb6-188ace556164");
                _pdomappingInfo = new RepoItemInfo(this, "PDOMapping", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@accessiblename='PDO Mapping']", 30000, null, "6edf855a-0cf1-4a29-a5c5-466e094064f2");
                _tabpagegeneralInfo = new RepoItemInfo(this, "TabPageGeneral", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_General']", 30000, null, "27cdb0fb-d1e0-4936-9c8b-dcf2f5142157");
                _namerow0Info = new RepoItemInfo(this, "NameRow0", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']//tree[@accessiblename='Not Available']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node0']/cell[@accessiblename='Name row 0']", 30000, null, "3991b51f-82f5-4b74-b947-32a806a8e8fc");
                _namerow01Info = new RepoItemInfo(this, "NameRow01", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']//tree[@accessiblerole='Outline']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node0']/cell[@accessiblename='Name row 0']", 30000, null, "e8d62e77-6c90-4c71-a120-24ccfcedab75");
                _parametersInfo = new RepoItemInfo(this, "Parameters", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@accessiblename='Parameters']", 30000, null, "bee2ef36-a072-4fd8-b7d8-ca0df112bc34");
                _buttonaddInfo = new RepoItemInfo(this, "ButtonAdd", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_Para']/?/?/container[@controlname='tableLayoutPanel12']/?/?/button[@accessiblename='Add']", 30000, null, "1de49f61-7cd2-40e2-8581-ae91b95bce00");
                _positionInfo = new RepoItemInfo(this, "Position", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']/?/?/container[@controlname='tableLayoutPanel1']/element[@controlname='cellMergeTreeList_Input']/element[@controltypename='VTLScrollBar']/scrollbar[@accessiblename='scroll bar']/indicator[@accessiblename='Position']", 30000, null, "1fa080ff-6ed3-4761-b411-38ff8f32a973");
                _namerow12Info = new RepoItemInfo(this, "NameRow12", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']//tree[@accessiblename='Not Available']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node12']/cell[@accessiblename='Name row 12']", 30000, null, "2e4f50cb-df5b-47d6-88af-c2c6bd1a837e");
                _position1Info = new RepoItemInfo(this, "Position1", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']/?/?/container[@controlname='tableLayoutPanel1']//scrollbar[@accessiblename='scroll bar']/indicator[@accessiblename='Position']", 30000, null, "ea15f725-33af-4c6c-92e2-fb9a617827e7");
                _namerow9Info = new RepoItemInfo(this, "NameRow9", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']//tree[@accessiblerole='Outline']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node9']/cell[@accessiblename='Name row 9']", 30000, null, "1796d183-4011-47b8-a2ae-c6d9743081e1");
                _iomappingInfo = new RepoItemInfo(this, "IOMapping", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@accessiblename='I/O Mapping']", 30000, null, "14fae1c7-cfb4-4b93-9bbd-f9f7dffab9c6");
                _symbolrow0Info = new RepoItemInfo(this, "SymbolRow0", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_IOMapping']//tree[@accessiblename='Select the Outputs']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node0']/cell[@accessiblename='Symbol row 0']", 30000, null, "36ef02e5-b85f-4c6e-b9f9-09476acc8747");
                _symbolrow1Info = new RepoItemInfo(this, "SymbolRow1", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_IOMapping']//tree[@accessiblename='Select the Outputs']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node1']/cell[@accessiblename='Symbol row 1']", 30000, null, "628521ee-010c-47b2-8706-b98b4906a501");
                _selecttheoutputsInfo = new RepoItemInfo(this, "SelectTheOutputs", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_IOMapping']//tree[@accessiblename='Select the Outputs']", 30000, null, "8c4e723c-8ec2-4bd4-a025-16c7dd0f2265");
                _initcommandsInfo = new RepoItemInfo(this, "InitCommands", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@accessiblename='Init Commands']", 30000, null, "0d6e0e50-57bb-4554-bcf0-ce0ee8b82f3d");
                _indexrow1Info = new RepoItemInfo(this, "IndexRow1", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_InitCmd']//tree[@accessiblename='Init Commands']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node1']/cell[@accessiblename='Index row 1']", 30000, null, "0ad3dac4-c59b-453f-95d7-9118976ec957");
                _deleteInfo = new RepoItemInfo(this, "Delete", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_InitCmd']/?/?/container[@controlname='tableLayoutPanel9']/?/?/button[@accessiblename='Delete']", 30000, null, "b59b259a-6c9c-4319-b6bd-e65f0dcb5ebd");
                _linedownInfo = new RepoItemInfo(this, "LineDown", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']/?/?/container[@controlname='tableLayoutPanel1']/element[@controlname='cellMergeTreeList_Input']/element[@controltypename='VTLScrollBar']/scrollbar[@accessiblename='scroll bar']/button[@accessiblename='Line Down']", 30000, null, "e92440b4-f9e3-4b15-aa90-28db0e81f5eb");
                _linedown1Info = new RepoItemInfo(this, "LineDown1", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']/?/?/container[@controlname='tableLayoutPanel1']//scrollbar[@accessiblename='scroll bar']/button[@accessiblename='Line Down']", 30000, null, "f3136958-2a22-4248-a2fe-5a4f8abcf177");
                _namerow15Info = new RepoItemInfo(this, "NameRow15", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']//tree[@accessiblerole='Outline']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node15']/cell[@accessiblename='Name row 15']", 30000, null, "de720847-aa6b-4a6d-9aab-2595bd0fb08e");
                _editInfo = new RepoItemInfo(this, "Edit", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']/?/?/container[@controlname='tableLayoutPanel3']/?/?/button[@accessiblename='Edit']", 30000, null, "ad6a8601-d866-4057-bb0e-a70200d88092");
                _tablelayoutpanel3Info = new RepoItemInfo(this, "TableLayoutPanel3", "container[@controlname='splitContainerControl']/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']/?/?/container[@controlname='tableLayoutPanel3']", 30000, null, "59629128-6636-49c9-b07e-b31adb616900");
                _namerow18Info = new RepoItemInfo(this, "NameRow18", "?/?/container[@controlname='panel2']//form[@controlname='SlaveConfigForm']/?/?/tabpage[@controlname='tabPage_PdoMapping']//tree[@accessiblerole='Outline']/container[@accessiblename='Data Panel']/treeitem[@accessiblename='Node18']/cell[@accessiblename='Name row 18']", 30000, null, "8dfee0b9-55ae-4a76-a2e4-37a765952622");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9e6d84de-866b-457e-bd99-dd691e0e98c6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9e6d84de-866b-457e-bd99-dd691e0e98c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("2d06c920-6777-4f22-b40b-350b0d7dfc05")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("2d06c920-6777-4f22-b40b-350b0d7dfc05")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The General item.
            /// </summary>
            [RepositoryItem("8a313465-c03e-497b-abb6-188ace556164")]
            public virtual Ranorex.TabPage General
            {
                get
                {
                    return _generalInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The General item info.
            /// </summary>
            [RepositoryItemInfo("8a313465-c03e-497b-abb6-188ace556164")]
            public virtual RepoItemInfo GeneralInfo
            {
                get
                {
                    return _generalInfo;
                }
            }

            /// <summary>
            /// The PDOMapping item.
            /// </summary>
            [RepositoryItem("6edf855a-0cf1-4a29-a5c5-466e094064f2")]
            public virtual Ranorex.TabPage PDOMapping
            {
                get
                {
                    return _pdomappingInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The PDOMapping item info.
            /// </summary>
            [RepositoryItemInfo("6edf855a-0cf1-4a29-a5c5-466e094064f2")]
            public virtual RepoItemInfo PDOMappingInfo
            {
                get
                {
                    return _pdomappingInfo;
                }
            }

            /// <summary>
            /// The TabPageGeneral item.
            /// </summary>
            [RepositoryItem("27cdb0fb-d1e0-4936-9c8b-dcf2f5142157")]
            public virtual Ranorex.TabPage TabPageGeneral
            {
                get
                {
                    return _tabpagegeneralInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabPageGeneral item info.
            /// </summary>
            [RepositoryItemInfo("27cdb0fb-d1e0-4936-9c8b-dcf2f5142157")]
            public virtual RepoItemInfo TabPageGeneralInfo
            {
                get
                {
                    return _tabpagegeneralInfo;
                }
            }

            /// <summary>
            /// The NameRow0 item.
            /// </summary>
            [RepositoryItem("3991b51f-82f5-4b74-b947-32a806a8e8fc")]
            public virtual Ranorex.Cell NameRow0
            {
                get
                {
                    return _namerow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NameRow0 item info.
            /// </summary>
            [RepositoryItemInfo("3991b51f-82f5-4b74-b947-32a806a8e8fc")]
            public virtual RepoItemInfo NameRow0Info
            {
                get
                {
                    return _namerow0Info;
                }
            }

            /// <summary>
            /// The NameRow01 item.
            /// </summary>
            [RepositoryItem("e8d62e77-6c90-4c71-a120-24ccfcedab75")]
            public virtual Ranorex.Cell NameRow01
            {
                get
                {
                    return _namerow01Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NameRow01 item info.
            /// </summary>
            [RepositoryItemInfo("e8d62e77-6c90-4c71-a120-24ccfcedab75")]
            public virtual RepoItemInfo NameRow01Info
            {
                get
                {
                    return _namerow01Info;
                }
            }

            /// <summary>
            /// The Parameters item.
            /// </summary>
            [RepositoryItem("bee2ef36-a072-4fd8-b7d8-ca0df112bc34")]
            public virtual Ranorex.TabPage Parameters
            {
                get
                {
                    return _parametersInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Parameters item info.
            /// </summary>
            [RepositoryItemInfo("bee2ef36-a072-4fd8-b7d8-ca0df112bc34")]
            public virtual RepoItemInfo ParametersInfo
            {
                get
                {
                    return _parametersInfo;
                }
            }

            /// <summary>
            /// The ButtonAdd item.
            /// </summary>
            [RepositoryItem("1de49f61-7cd2-40e2-8581-ae91b95bce00")]
            public virtual Ranorex.Button ButtonAdd
            {
                get
                {
                    return _buttonaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAdd item info.
            /// </summary>
            [RepositoryItemInfo("1de49f61-7cd2-40e2-8581-ae91b95bce00")]
            public virtual RepoItemInfo ButtonAddInfo
            {
                get
                {
                    return _buttonaddInfo;
                }
            }

            /// <summary>
            /// The Position item.
            /// </summary>
            [RepositoryItem("1fa080ff-6ed3-4761-b411-38ff8f32a973")]
            public virtual Ranorex.Indicator Position
            {
                get
                {
                    return _positionInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The Position item info.
            /// </summary>
            [RepositoryItemInfo("1fa080ff-6ed3-4761-b411-38ff8f32a973")]
            public virtual RepoItemInfo PositionInfo
            {
                get
                {
                    return _positionInfo;
                }
            }

            /// <summary>
            /// The NameRow12 item.
            /// </summary>
            [RepositoryItem("2e4f50cb-df5b-47d6-88af-c2c6bd1a837e")]
            public virtual Ranorex.Cell NameRow12
            {
                get
                {
                    return _namerow12Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NameRow12 item info.
            /// </summary>
            [RepositoryItemInfo("2e4f50cb-df5b-47d6-88af-c2c6bd1a837e")]
            public virtual RepoItemInfo NameRow12Info
            {
                get
                {
                    return _namerow12Info;
                }
            }

            /// <summary>
            /// The Position1 item.
            /// </summary>
            [RepositoryItem("ea15f725-33af-4c6c-92e2-fb9a617827e7")]
            public virtual Ranorex.Indicator Position1
            {
                get
                {
                    return _position1Info.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The Position1 item info.
            /// </summary>
            [RepositoryItemInfo("ea15f725-33af-4c6c-92e2-fb9a617827e7")]
            public virtual RepoItemInfo Position1Info
            {
                get
                {
                    return _position1Info;
                }
            }

            /// <summary>
            /// The NameRow9 item.
            /// </summary>
            [RepositoryItem("1796d183-4011-47b8-a2ae-c6d9743081e1")]
            public virtual Ranorex.Cell NameRow9
            {
                get
                {
                    return _namerow9Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NameRow9 item info.
            /// </summary>
            [RepositoryItemInfo("1796d183-4011-47b8-a2ae-c6d9743081e1")]
            public virtual RepoItemInfo NameRow9Info
            {
                get
                {
                    return _namerow9Info;
                }
            }

            /// <summary>
            /// The IOMapping item.
            /// </summary>
            [RepositoryItem("14fae1c7-cfb4-4b93-9bbd-f9f7dffab9c6")]
            public virtual Ranorex.TabPage IOMapping
            {
                get
                {
                    return _iomappingInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The IOMapping item info.
            /// </summary>
            [RepositoryItemInfo("14fae1c7-cfb4-4b93-9bbd-f9f7dffab9c6")]
            public virtual RepoItemInfo IOMappingInfo
            {
                get
                {
                    return _iomappingInfo;
                }
            }

            /// <summary>
            /// The SymbolRow0 item.
            /// </summary>
            [RepositoryItem("36ef02e5-b85f-4c6e-b9f9-09476acc8747")]
            public virtual Ranorex.Cell SymbolRow0
            {
                get
                {
                    return _symbolrow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The SymbolRow0 item info.
            /// </summary>
            [RepositoryItemInfo("36ef02e5-b85f-4c6e-b9f9-09476acc8747")]
            public virtual RepoItemInfo SymbolRow0Info
            {
                get
                {
                    return _symbolrow0Info;
                }
            }

            /// <summary>
            /// The SymbolRow1 item.
            /// </summary>
            [RepositoryItem("628521ee-010c-47b2-8706-b98b4906a501")]
            public virtual Ranorex.Cell SymbolRow1
            {
                get
                {
                    return _symbolrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The SymbolRow1 item info.
            /// </summary>
            [RepositoryItemInfo("628521ee-010c-47b2-8706-b98b4906a501")]
            public virtual RepoItemInfo SymbolRow1Info
            {
                get
                {
                    return _symbolrow1Info;
                }
            }

            /// <summary>
            /// The SelectTheOutputs item.
            /// </summary>
            [RepositoryItem("8c4e723c-8ec2-4bd4-a025-16c7dd0f2265")]
            public virtual Ranorex.Tree SelectTheOutputs
            {
                get
                {
                    return _selecttheoutputsInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The SelectTheOutputs item info.
            /// </summary>
            [RepositoryItemInfo("8c4e723c-8ec2-4bd4-a025-16c7dd0f2265")]
            public virtual RepoItemInfo SelectTheOutputsInfo
            {
                get
                {
                    return _selecttheoutputsInfo;
                }
            }

            /// <summary>
            /// The InitCommands item.
            /// </summary>
            [RepositoryItem("0d6e0e50-57bb-4554-bcf0-ce0ee8b82f3d")]
            public virtual Ranorex.TabPage InitCommands
            {
                get
                {
                    return _initcommandsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The InitCommands item info.
            /// </summary>
            [RepositoryItemInfo("0d6e0e50-57bb-4554-bcf0-ce0ee8b82f3d")]
            public virtual RepoItemInfo InitCommandsInfo
            {
                get
                {
                    return _initcommandsInfo;
                }
            }

            /// <summary>
            /// The IndexRow1 item.
            /// </summary>
            [RepositoryItem("0ad3dac4-c59b-453f-95d7-9118976ec957")]
            public virtual Ranorex.Cell IndexRow1
            {
                get
                {
                    return _indexrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The IndexRow1 item info.
            /// </summary>
            [RepositoryItemInfo("0ad3dac4-c59b-453f-95d7-9118976ec957")]
            public virtual RepoItemInfo IndexRow1Info
            {
                get
                {
                    return _indexrow1Info;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("b59b259a-6c9c-4319-b6bd-e65f0dcb5ebd")]
            public virtual Ranorex.Button Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("b59b259a-6c9c-4319-b6bd-e65f0dcb5ebd")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The LineDown item.
            /// </summary>
            [RepositoryItem("e92440b4-f9e3-4b15-aa90-28db0e81f5eb")]
            public virtual Ranorex.Button LineDown
            {
                get
                {
                    return _linedownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LineDown item info.
            /// </summary>
            [RepositoryItemInfo("e92440b4-f9e3-4b15-aa90-28db0e81f5eb")]
            public virtual RepoItemInfo LineDownInfo
            {
                get
                {
                    return _linedownInfo;
                }
            }

            /// <summary>
            /// The LineDown1 item.
            /// </summary>
            [RepositoryItem("f3136958-2a22-4248-a2fe-5a4f8abcf177")]
            public virtual Ranorex.Button LineDown1
            {
                get
                {
                    return _linedown1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LineDown1 item info.
            /// </summary>
            [RepositoryItemInfo("f3136958-2a22-4248-a2fe-5a4f8abcf177")]
            public virtual RepoItemInfo LineDown1Info
            {
                get
                {
                    return _linedown1Info;
                }
            }

            /// <summary>
            /// The NameRow15 item.
            /// </summary>
            [RepositoryItem("de720847-aa6b-4a6d-9aab-2595bd0fb08e")]
            public virtual Ranorex.Cell NameRow15
            {
                get
                {
                    return _namerow15Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NameRow15 item info.
            /// </summary>
            [RepositoryItemInfo("de720847-aa6b-4a6d-9aab-2595bd0fb08e")]
            public virtual RepoItemInfo NameRow15Info
            {
                get
                {
                    return _namerow15Info;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("ad6a8601-d866-4057-bb0e-a70200d88092")]
            public virtual Ranorex.Button Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("ad6a8601-d866-4057-bb0e-a70200d88092")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The TableLayoutPanel3 item.
            /// </summary>
            [RepositoryItem("59629128-6636-49c9-b07e-b31adb616900")]
            public virtual Ranorex.Container TableLayoutPanel3
            {
                get
                {
                    return _tablelayoutpanel3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TableLayoutPanel3 item info.
            /// </summary>
            [RepositoryItemInfo("59629128-6636-49c9-b07e-b31adb616900")]
            public virtual RepoItemInfo TableLayoutPanel3Info
            {
                get
                {
                    return _tablelayoutpanel3Info;
                }
            }

            /// <summary>
            /// The NameRow18 item.
            /// </summary>
            [RepositoryItem("8dfee0b9-55ae-4a76-a2e4-37a765952622")]
            public virtual Ranorex.Cell NameRow18
            {
                get
                {
                    return _namerow18Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NameRow18 item info.
            /// </summary>
            [RepositoryItemInfo("8dfee0b9-55ae-4a76-a2e4-37a765952622")]
            public virtual RepoItemInfo NameRow18Info
            {
                get
                {
                    return _namerow18Info;
                }
            }
        }

    }
}